spring:
  application:
    name: ms-ingestao
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/sus-hackathon}

sus:
  security:
    webhook:
      username: ${WEBHOOK_BASIC_USER:twilio}
      password: ${WEBHOOK_BASIC_PASSWORD:teste123}

server:
  port: 8080
